services:
    postgres:
        container_name: service-postgres
        image: postgres:latest
        environment: &db_env
            POSTGRES_DB: never_forget_bot_db-1
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - 5432
        volumes:
            - ./postgresql/schemas:/docker-entrypoint-initdb.d
            - ./.pgdata:/var/lib/postgresql/data
        networks:
            - postgres

    never_forget_bot-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        env_file:
            - path: .env
        environment:
            <<: *db_env
            PREFIX: ${PREFIX:-~/.local}
            CCACHE_DIR: /never_forget_bot/.ccache
            CORES_DIR: /cores
        volumes:
            - .:/never_forget_bot:rw
            - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
            - 8080:8080
        working_dir: /never_forget_bot
        depends_on:
            - postgres
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
