services:
    postgres:
        image: postgres:15
        env_file:
            - .env
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./migrations:/docker-entrypoint-initdb.d
        ports:
            - "${POSTGRES_PORT}:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        networks:
            - postgres

    app:
        build: .
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - postgres
        env_file:
            - .env
        ports:
            - "8080:8080"
        restart: always

volumes:
    db-data:

networks:
    postgres:
        driver: bridge

