services:
    postgres:
        container_name: service-postgres
        image: postgres:latest
        env_file:
            - .env
        ports:
            - 5432
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./postgresql/schemas:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        networks:
            - postgres

    never_forget_bot-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        env_file:
            - .env
        environment:
            PREFIX: ${PREFIX:-~/.local}
            CCACHE_DIR: /never_forget_bot/.ccache
            CORES_DIR: /cores
        volumes:
            - .:/never_forget_bot:rw
            - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
            - 8080:8080
        working_dir: /never_forget_bot
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - postgres

volumes:
    db-data:

networks:
    postgres:
        driver: bridge

