name: CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install docker-compose
      run: |
        sudo apt update
        sudo apt install -y docker-compose
    - name: Build image
      run: |
        echo "${{ secrets.ENV }}" > .env;
        git submodule update --init
        sudo make docker-build-release
    - name: Test
      run: |
        sudo make docker-test-release
  deploy:
    name: Deploy
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy application to remote server
      run: |
        echo "${{ secrets.ENV }}" > .env;
        tar -czf app.tar.gz * .env
        ls -la
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
        sudo chmod 600 ~/.ssh/deploy_key
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no app.tar.gz ubuntu@158.160.128.8:~/app
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ubuntu@158.160.128.8 "
        cd app
        tar -xzf app.tar.gz
        sudo make docker-start-release
        exit" 
