name: CD

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare env file
      run: |
        echo "${{ secrets.ENV }}" > .env;
    #- name: Install docker-compose
    #  run: |
    #    sudo apt update
    #    sudo apt install -y docker-compose
    #- name: Build image
    #  run: |
    #    git submodule update --init
    #    sudo make docker
    #- name: Test
    #  run: |
    #    sudo make docker-test
    - name: Deploy application to remote server
      run: |
        tar -czf app.tar.gz *
        ls -la
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
        sudo chmod 600 ~/.ssh/deploy_key
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no app.tar.gz ubuntu@158.160.128.8
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ubuntu@158.160.128.8 "
        tar -xzf app.tar.gz
        make docker-up
        exit" 
